import mongoose from 'mongoose';
import { env, validateEnv } from '../config/env';
import { Trade } from '../models/Trade';
import { generateSyntheticTradesForAll } from './generateSyntheticTrades';
import { scoreTrade, computeArrivalSlippageBps } from '../scoring/engine';
import { EnrichedTrade } from '../types';

validateEnv();

const DEMO_USERS = ['demo-aggressive', 'demo-moderate', 'demo-disciplined'];

// ── Helpers ──────────────────────────────────────────────────────────────────

/** random() in [min, max) */
function rand(min: number, max: number): number {
    return min + Math.random() * (max - min);
}

/**
 * Per-symbol spread ranges (bps) matching the spec.
 * These are intentionally conservative retail estimates, not live order-book data.
 */
function spreadBpsForSymbol(symbol: string): number {
    if (symbol === 'BTCUSDT') return rand(0.8, 1.8);
    if (symbol === 'ETHUSDT') return rand(1.0, 2.2);
    if (symbol === 'BNBUSDT') return rand(1.5, 3.0);
    if (symbol === 'SOLUSDT') return rand(2.0, 4.0);
    return rand(1.0, 3.0); // sensible fallback for other symbols
}

/**
 * Per-symbol arrival-price noise factor (fraction of executionPrice).
 * Tighter for BTC (more liquid), wider for alt coins.
 */
function arrivalNoiseFraction(symbol: string): number {
    if (symbol === 'BTCUSDT') return rand(-0.002, 0.002);
    if (symbol === 'ETHUSDT') return rand(-0.003, 0.003);
    // BNB / SOL / anything else
    return rand(-0.005, 0.005);
}

/**
 * Attach synthetic market-data fields and call scoreTrade() in-process.
 * Returns a plain object ready for MongoDB upsert (no Mongoose Document overhead).
 */
function enrichAndScore<T extends {
    executionPrice: number;
    symbol: string;
    side: 'BUY' | 'SELL';
    isMaker: boolean;
    executedAt: Date | string;
}>(trade: T): T & {
    arrivalPriceProxy: number;
    vwap5min: number;
    spreadBps: number;
    arrivalSlippageBps: number;
    slippageScore: number;
    feeScore: number;
    timingScore: number;
    exchangeScore: number;
    fillScore: number;
    fillGrade: 'A' | 'B' | 'C' | 'D' | 'F';
} {
    const arrivalPriceProxy = trade.executionPrice * (1 + arrivalNoiseFraction(trade.symbol));
    // vwap5min sits very close to the arrival price with slight additional noise
    const vwap5min           = arrivalPriceProxy * (1 + rand(-0.001, 0.001));
    const spreadBps          = spreadBpsForSymbol(trade.symbol);
    const arrivalSlippageBps = computeArrivalSlippageBps(
        trade.executionPrice,
        arrivalPriceProxy,
        trade.side
    );

    // scoreTrade requires a proper Date for executedAt
    const executedAt = trade.executedAt instanceof Date
        ? trade.executedAt
        : new Date(trade.executedAt);

    // Build the minimal EnrichedTrade the scoring engine needs
    const forScoring: EnrichedTrade = {
        ...(trade as any),
        executedAt,
        arrivalPriceProxy,
        vwap5min,
        spreadBps,
    };

    const scores = scoreTrade(forScoring);

    return {
        ...trade,
        arrivalPriceProxy,
        vwap5min,
        spreadBps,
        arrivalSlippageBps,
        ...scores,
    };
}

// ── Main ─────────────────────────────────────────────────────────────────────

async function run() {
    await mongoose.connect(env.mongoDbUri);
    console.log('MongoDB connected');

    console.log('Generating synthetic trades directly from real market data...');
    const tradesByProfile = await generateSyntheticTradesForAll();

    console.log('Dropping existing demo trades...');
    await Trade.deleteMany({ userId: { $in: DEMO_USERS } });

    let totalInserted = 0;

    for (const [profileId, trades] of Object.entries(tradesByProfile)) {
        if (!trades || trades.length === 0) continue;

        const symbolCounts: Record<string, number> = {};
        let inserted = 0;

        for (const raw of trades) {
            // Convert executedAt string → Date before enrichment
            const trade = { ...raw, executedAt: new Date(raw.executedAt) };
            const enriched = enrichAndScore(trade);

            const result = await Trade.updateOne(
                { userId: enriched.userId, exchange: enriched.exchange, tradeId: enriched.tradeId },
                { $setOnInsert: enriched },
                { upsert: true }
            );
            if (result.upsertedCount > 0) inserted++;

            symbolCounts[enriched.symbol] = (symbolCounts[enriched.symbol] || 0) + 1;
        }

        const breakdown = Object.entries(symbolCounts)
            .map(([sym, count]) => `${count} ${sym}`)
            .join(', ');

        console.log(`demo-${profileId}: ${breakdown} = ${inserted} total`);
        totalInserted += inserted;
    }

    // ── demo-bybit ──────────────────────────────────────────────────────────
    // Standalone Bybit synthetic block: not generated by generateSyntheticTradesForAll
    // (which is Binance-only), so we build + enrich + upsert the 50 documents here directly.
    const BYBIT_USER      = 'demo-bybit';
    const NOW_MS          = Date.now();
    const THIRTY_DAYS_MS  = 30 * 24 * 60 * 60 * 1000;

    await Trade.deleteMany({ userId: BYBIT_USER });

    let bybitInserted = 0;

    for (let i = 0; i < 50; i++) {
        const isBtc   = i % 2 === 0;
        const symbol  = isBtc ? 'BTCUSDT' : 'ETHUSDT';
        const side    = (i % 2 === 0 ? 'BUY' : 'SELL') as 'BUY' | 'SELL';
        const isMaker = i % 2 === 0; // every other trade is a maker

        // Random price within Bybit-realistic ranges
        const executionPrice = isBtc
            ? 40000 + Math.random() * 5000   // 40 000 – 45 000
            : 2200  + Math.random() * 300;   // 2 200  – 2 500

        const quantity  = 0.01 + Math.random() * 0.09;          // 0.01 – 0.10
        const notional  = executionPrice * quantity;

        // Bybit fee schedule: 0.10 % maker / 0.10 % taker
        const fee       = notional * 0.001;

        // Random timestamp within the last 30 days
        const executedAt = new Date(NOW_MS - Math.random() * THIRTY_DAYS_MS);

        const raw = {
            userId:     BYBIT_USER,
            exchange:   'bybit' as const,
            symbol,
            tradeId:    `bybit-synthetic-${i}`,
            orderId:    `bybit-order-${i}`,
            side,
            // Maker orders rest on the book → LIMIT; takers cross the spread → MARKET
            orderType:  (isMaker ? 'LIMIT' : 'MARKET') as 'LIMIT' | 'MARKET',
            isMaker,
            executionPrice,
            quantity,
            notional,
            fee,
            feeAsset:   'USDT',
            executedAt,
        };

        const enriched = enrichAndScore(raw);

        const result = await Trade.updateOne(
            { userId: enriched.userId, exchange: 'bybit', tradeId: enriched.tradeId },
            { $setOnInsert: enriched },
            { upsert: true }
        );
        if (result.upsertedCount > 0) bybitInserted++;
    }

    console.log(`demo-bybit: 25 BTCUSDT, 25 ETHUSDT = ${bybitInserted} total`);
    totalInserted += bybitInserted;
    // ────────────────────────────────────────────────────────────────────────

    // ── demo-okx ─────────────────────────────────────────────────────────────
    const OKX_USER        = 'demo-okx';
    await Trade.deleteMany({ userId: OKX_USER });

    let okxInserted = 0;

    for (let i = 0; i < 50; i++) {
        const isBtc   = i % 2 === 0;
        const instId  = isBtc ? 'BTC-USDT' : 'ETH-USDT';
        const symbol  = instId.replace('-', '');
        const side    = (i % 2 === 0 ? 'BUY' : 'SELL') as 'BUY' | 'SELL';
        const isMaker = i % 2 === 0;

        const executionPrice = isBtc
            ? 40000 + Math.random() * 5000
            : 2200  + Math.random() * 300;

        const quantity  = 0.01 + Math.random() * 0.09;
        const notional  = executionPrice * quantity;
        const fee       = notional * (isMaker ? 0.0008 : 0.001);
        const executedAt = new Date(NOW_MS - Math.random() * THIRTY_DAYS_MS);

        const raw = {
            userId:     OKX_USER,
            exchange:   'okx' as const,
            symbol,
            tradeId:    `okx-synthetic-${i}`,
            orderId:    `okx-order-${i}`,
            side,
            orderType:  (isMaker ? 'LIMIT' : 'MARKET') as 'LIMIT' | 'MARKET',
            isMaker,
            execType:   (isMaker ? 'M' : 'T') as 'M' | 'T',
            executionPrice,
            quantity,
            notional,
            fee,
            feeAsset:   'USDT',
            executedAt,
        };

        const enriched = enrichAndScore(raw);

        const result = await Trade.updateOne(
            { userId: enriched.userId, exchange: 'okx', tradeId: enriched.tradeId },
            { $setOnInsert: enriched },
            { upsert: true }
        );
        if (result.upsertedCount > 0) okxInserted++;
    }

    console.log(`demo-okx: 25 BTCUSDT, 25 ETHUSDT = ${okxInserted} total`);
    totalInserted += okxInserted;
    // ─────────────────────────────────────────────────────────────────────────

    // ── demo-multi ───────────────────────────────────────────────────────────
    const MULTI_USER = 'demo-multi';
    await Trade.deleteMany({ userId: MULTI_USER });

    let multiInserted = 0;

    const multiExchanges = [
        { name: 'binance', trades: 30, slippageBase: 6, makerRatio: 0.5 },
        { name: 'bybit', trades: 30, slippageBase: 3, makerRatio: 0.6 },
        { name: 'okx', trades: 30, slippageBase: 8, makerRatio: 0.4 }
    ];

    for (const ex of multiExchanges) {
        for (let i = 0; i < ex.trades; i++) {
            const isBtc = i % 2 === 0;
            const symbol = isBtc ? 'BTCUSDT' : 'ETHUSDT';
            const side = (i % 2 === 0 ? 'BUY' : 'SELL') as 'BUY' | 'SELL';
            
            const isMaker = (i / ex.trades) < ex.makerRatio;
            
            const executionPrice = isBtc
                ? 40000 + Math.random() * 5000
                : 2200 + Math.random() * 300;
            
            const quantity = 0.01 + Math.random() * 0.09;
            const notional = executionPrice * quantity;
            const feeRate = (ex.name === 'okx' && isMaker) ? 0.0008 : 0.001;
            const fee = notional * feeRate;
            const executedAt = new Date(Date.now() - Math.random() * (30 * 24 * 60 * 60 * 1000));
            
            const raw = {
                userId: MULTI_USER,
                exchange: ex.name as any,
                symbol,
                tradeId: `multi-${ex.name}-${i}`,
                orderId: `multi-order-${ex.name}-${i}`,
                side,
                orderType: (isMaker ? 'LIMIT' : 'MARKET') as 'LIMIT' | 'MARKET',
                isMaker,
                execType: (isMaker ? 'M' : 'T') as 'M' | 'T',
                executionPrice,
                quantity,
                notional,
                fee,
                feeAsset: 'USDT',
                executedAt,
            };

            const enriched = enrichAndScore(raw);
            
            const desiredSlippage = ex.slippageBase + (Math.random() * 2 - 1);
            enriched.arrivalSlippageBps = desiredSlippage;
            const scoreAdjustment = (5 - desiredSlippage) * 2;
            enriched.fillScore = Math.min(100, Math.max(0, enriched.fillScore + scoreAdjustment));
            enriched.slippageScore = Math.min(100, Math.max(0, enriched.slippageScore + scoreAdjustment));

            const result = await Trade.updateOne(
                { userId: enriched.userId, exchange: ex.name, tradeId: enriched.tradeId },
                { $setOnInsert: enriched },
                { upsert: true }
            );
            if (result.upsertedCount > 0) multiInserted++;
        }
    }

    console.log(`demo-multi: ${multiInserted} total across binance, bybit, okx`);
    totalInserted += multiInserted;
    // ─────────────────────────────────────────────────────────────────────────

    console.log(`\nSeed Complete! Total new trades injected: ${totalInserted}`);
    process.exit(0);
}

run().catch(err => {
    console.error('Seed script failed:', err);
    process.exit(1);
});

