import PDFDocument from 'pdfkit';

export class ReportService {
  static generateReport(
    auditData: any,
    attributionData: any,
    worstTrades: any[],
    comparisonData?: any
  ): PDFDocument {
    const doc = new PDFDocument({ size: 'A4', margin: 50, bufferPages: true, autoFirstPage: false });

    const gold = '#c9b99a';
    const dark = '#0d0d0b';
    const grey = '#888078';
    const white = '#ede8e0';
    const pageW = 595.28;
    const pageH = 841.89;

    // Helper for background — call immediately after addPage
    const drawBackground = () => {
      doc.rect(0, 0, pageW, pageH).fill(dark);
    };

    // Rating bands aligned with dashboard (getScoreLabel)
    const getRating = (s: number) => {
      if (s >= 90) return 'EXCELLENT';
      if (s >= 75) return 'GOOD';
      if (s >= 60) return 'AVERAGE';
      if (s >= 40) return 'POOR';
      return 'CRITICAL';
    };

    // Bar color bands aligned with dashboard (getScoreColor)
    const getBarColor = (s: number) => {
      if (s >= 80) return '#4ade80';
      if (s >= 60) return '#fcd34d';
      if (s >= 40) return '#f97316';
      return '#ef4444';
    };

    const getExchangeColor = (ex: string) => {
      const e = (ex || '').toLowerCase();
      if (e === 'binance') return '#F0B90B';
      if (e === 'bybit') return '#F7A600';
      if (e === 'okx') return '#2dd4bf';
      return '#ede8e0';
    };

    // ─────────────────────────────────────────────────────────
    // PAGE 1 — COVER
    // ─────────────────────────────────────────────────────────
    doc.addPage({ size: 'A4', margin: 50 });
    drawBackground();

    doc.fillColor(gold).font('Courier-Bold').fontSize(48).text('FILLSCORE', 50, 100);
    doc.fillColor(grey).font('Courier').fontSize(14).text('EXECUTION QUALITY AUDIT REPORT', 50, 160);

    const grade = auditData.fillGrade || 'N/A';
    const score = auditData.avgFillScore != null ? Math.round(auditData.avgFillScore) : 0;

    // Thin line above grade
    doc.moveTo(50, 300).lineTo(pageW - 50, 300).lineWidth(0.5).stroke(grey);

    doc.fillColor(gold).font('Courier-Bold').fontSize(120).text(grade, 50, 330, { align: 'center', width: pageW - 100 });
    doc.fillColor(white).font('Courier').fontSize(24).text(`${score} / 100`, 50, 460, { align: 'center', width: pageW - 100 });

    // Thin line below
    doc.moveTo(50, 510).lineTo(pageW - 50, 510).lineWidth(0.5).stroke(grey);

    // Period and Exchange
    const startStr = auditData.period?.start ? new Date(auditData.period.start).toLocaleDateString('en-US', { month: 'short', day: 'numeric' }) : '';
    const endStr = auditData.period?.end ? new Date(auditData.period.end).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }) : '';
    const periodStr = startStr && endStr ? `${startStr} - ${endStr}` : 'All Time';
    let exStr = (auditData.exchange || 'ALL').toUpperCase();
    if (exStr === 'MULTI') exStr = 'BINANCE · BYBIT · OKX';

    doc.fillColor(grey).font('Courier').fontSize(12).text(periodStr, 50, pageH - 150);
    doc.fillColor(grey).font('Courier').fontSize(12).text(exStr, 50, pageH - 134);

    // Cover footer — positioned absolutely at bottom of page 1
    doc.fillColor(grey).font('Courier').fontSize(8).text(
      'Generated by FillScore · AES-256-GCM encrypted · Read-only analysis',
      50, pageH - 60, { align: 'center', width: pageW - 100 }
    );

    // ─────────────────────────────────────────────────────────
    // PAGE 2 — COMPONENT SCORES + COSTS + METRICS
    // ─────────────────────────────────────────────────────────
    doc.addPage({ size: 'A4', margin: 50 });
    drawBackground();

    doc.fillColor(white).font('Courier-Bold').fontSize(18).text('COMPONENT SCORES', 50, 50);

    let cy = 90;

    const drawRow = (label: string, weight: string, s: number, detail: string) => {
      doc.fillColor(white).font('Courier-Bold').fontSize(12).text(label, 50, cy, { width: 100 });
      doc.fillColor(grey).font('Courier').fontSize(12).text(weight, 150, cy);
      doc.fillColor(gold).font('Courier-Bold').fontSize(12).text(Math.round(s).toString(), 200, cy);
      doc.fillColor(white).font('Courier').fontSize(12).text(getRating(s), 250, cy, { width: 100 });
      doc.fillColor(grey).font('Courier').fontSize(12).text(detail, 350, cy);

      const barY = cy + 16;
      doc.rect(50, barY, 400, 4).fill('#1a1917');
      doc.rect(50, barY, 400 * (Math.max(0, Math.min(100, s)) / 100), 4).fill(getBarColor(s));

      cy = barY + 30;
    };

    // Compute component scores from audit.breakdown (same formula as dashboard)
    const bd = auditData.breakdown || {};
    const slippageScore = Math.min(100, Math.max(0, Math.round(100 - ((bd.avgSlippageBps || 0) * 6))));
    const feeScore = Math.min(100, Math.max(0, Math.round((bd.makerRatio || 0) * 100)));
    const timingScore = Math.min(100, Math.max(0, (bd.worstHour >= 22 || bd.worstHour <= 7) ? 65 : 85));
    const spreadScore = Math.min(100, Math.max(0, Math.round(100 - ((bd.avgFeeDragBps || 0) * 2))));

    const slippageAvg = bd.avgSlippageBps ? bd.avgSlippageBps.toFixed(1) + ' bps avg' : '';
    const feeRatio = bd.makerRatio != null ? Math.round(bd.makerRatio * 100) + '% maker ratio' : '';
    const timingPeak = bd.bestHour != null ? `Peak: ${bd.bestHour.toString().padStart(2, '0')}:00 UTC` : '';
    const spreadAvg = bd.avgFeeDragBps ? bd.avgFeeDragBps.toFixed(1) + ' bps drag' : '';

    drawRow('SLIPPAGE', '35%', slippageScore, slippageAvg);
    drawRow('FEE EFF.', '25%', feeScore, feeRatio);
    drawRow('TIMING', '25%', timingScore, timingPeak);
    drawRow('SPREAD', '15%', spreadScore, spreadAvg);

    cy += 30;
    doc.fillColor(white).font('Courier-Bold').fontSize(18).text('EXECUTION COST BREAKDOWN', 50, cy);
    cy += 30;

    const attr = attributionData || {};
    doc.fillColor(grey).font('Courier').fontSize(12);
    doc.text(`Slippage cost : $${(attr.slippageCost || 0).toFixed(2)}`, 50, cy); cy += 16;
    doc.text(`Fee cost      : $${(attr.feeCost || 0).toFixed(2)}`, 50, cy); cy += 16;
    doc.text(`Timing cost   : $${(attr.timingCost || 0).toFixed(2)}`, 50, cy); cy += 16;
    doc.text(`Spread cost   : $${(attr.spreadCost || 0).toFixed(2)}`, 50, cy); cy += 24;
    doc.fillColor(gold).font('Courier-Bold').fontSize(12).text(`TOTAL COST    : $${(attr.totalCost || 0).toFixed(2)}`, 50, cy);
    cy += 40;

    doc.fillColor(white).font('Courier-Bold').fontSize(18).text('KEY METRICS', 50, cy);
    cy += 30;

    doc.fillColor(grey).font('Courier').fontSize(12);
    doc.text(`Total Volume    : $${(auditData.totalNotional || 0).toLocaleString(undefined, { maximumFractionDigits: 0 })}`, 50, cy); cy += 16;
    doc.text(`Trades Analysed : ${auditData.totalTrades || 0}`, 50, cy); cy += 16;
    if (bd.bestSymbol) { doc.text(`Best Symbol     : ${bd.bestSymbol}`, 50, cy); cy += 16; }
    if (bd.worstSymbol) { doc.text(`Worst Symbol    : ${bd.worstSymbol}`, 50, cy); cy += 16; }
    if (bd.bestHour != null) { doc.text(`Best Hour       : ${bd.bestHour.toString().padStart(2, '0')}:00 UTC`, 50, cy); cy += 16; }
    if (bd.worstHour != null) { doc.text(`Worst Hour      : ${bd.worstHour.toString().padStart(2, '0')}:00 UTC`, 50, cy); }

    // ─────────────────────────────────────────────────────────
    // PAGE 3 — WORST TRADES TABLE
    // ─────────────────────────────────────────────────────────
    doc.addPage({ size: 'A4', margin: 50 });
    drawBackground();

    doc.fillColor(white).font('Courier-Bold').fontSize(18).text('WORST PERFORMING TRADES', 50, 50);

    const tableTop = 90;
    const colX = [50, 110, 170, 230, 280, 360, 440, 490];
    const cols = ['DATE', 'SYMBOL', 'EXCH', 'SIDE', 'NOTIONAL', 'SLIP BPS', 'SCORE', 'GRD'];

    doc.fillColor(grey).font('Courier-Bold').fontSize(9);
    cols.forEach((col, i) => doc.text(col, colX[i], tableTop));

    let ty = tableTop + 20;

    worstTrades.forEach((t, i) => {
      doc.rect(50, ty - 5, pageW - 100, 20).fill(i % 2 === 0 ? '#1a1917' : dark);

      const dt = new Date(t.executedAt);
      const dateStr = dt.toISOString().split('T')[0].substring(5);

      doc.fillColor(white).font('Courier').fontSize(9);
      doc.text(dateStr, colX[0], ty);
      doc.text((t.symbol || '').substring(0, 8), colX[1], ty);
      doc.text((t.exchange || '').substring(0, 5).toUpperCase(), colX[2], ty);
      doc.text((t.side || '').toUpperCase(), colX[3], ty);
      doc.text(`$${Math.round(t.notional || t.notionalValue || 0)}`, colX[4], ty);
      doc.text((t.slippageBps || t.arrivalSlippageBps || 0).toFixed(1), colX[5], ty);
      doc.text(Math.round(t.fillScore || 0).toString(), colX[6], ty);

      const tGrade = t.fillGrade || 'F';
      const gradeColor = tGrade === 'A' ? '#4ade80' : tGrade === 'B' ? '#86efac' : tGrade === 'C' ? '#fcd34d' : tGrade === 'D' ? '#f97316' : '#ef4444';
      doc.fillColor(gradeColor).font('Courier-Bold').fontSize(9).text(tGrade, colX[7], ty);

      ty += 20;
    });

    // ─────────────────────────────────────────────────────────
    // PAGE 4 (conditional) — VENUE COMPARISON (multi-exchange only)
    // ─────────────────────────────────────────────────────────
    if (comparisonData && comparisonData.exchanges && comparisonData.exchanges.length > 1) {
      doc.addPage({ size: 'A4', margin: 50 });
      drawBackground();

      doc.fillColor(white).font('Courier-Bold').fontSize(18).text('VENUE COMPARISON', 50, 50);

      // Venue alpha headline
      doc.fillColor(white).font('Courier').fontSize(12).text(
        `Routing to `, 50, 90,
        { continued: true }
      );
      doc.fillColor(getExchangeColor(comparisonData.bestExchange)).font('Courier-Bold').text(
        comparisonData.bestExchange.toUpperCase(),
        { continued: true }
      );
      doc.fillColor(white).font('Courier').text(
        ` instead of `,
        { continued: true }
      );
      doc.fillColor(getExchangeColor(comparisonData.worstExchange)).font('Courier-Bold').text(
        comparisonData.worstExchange.toUpperCase(),
        { continued: true }
      );
      doc.fillColor(white).font('Courier').text(
        ` saves you ~${comparisonData.venueAlphaBps.toFixed(1)} bps on slippage.`
      );

      // Venue cards
      let vy = 140;
      const cardW = (pageW - 100 - 20) / comparisonData.exchanges.length; // evenly spaced

      comparisonData.exchanges.forEach((ex: any, i: number) => {
        const cardX = 50 + i * (cardW + 10);
        const isBest = ex.exchange === comparisonData.bestExchange;

        // Card background
        doc.rect(cardX, vy, cardW, 160).fill('#1a1917');
        // Top accent line
        doc.rect(cardX, vy, cardW, 2).fill(getExchangeColor(ex.exchange));

        // Exchange name
        doc.fillColor(getExchangeColor(ex.exchange)).font('Courier-Bold').fontSize(12)
          .text(ex.exchange.toUpperCase(), cardX + 10, vy + 12, { width: cardW - 20 });

        if (isBest) {
          doc.fillColor('#4ade80').font('Courier-Bold').fontSize(8)
            .text('BEST VENUE', cardX + 10, vy + 28, { width: cardW - 20 });
        }

        const labelY = vy + 46;
        const valX = cardX + 10;
        const vw = cardW - 20;

        doc.fillColor(grey).font('Courier').fontSize(8);
        doc.text('SCORE', valX, labelY, { width: vw });
        doc.fillColor(white).font('Courier-Bold').fontSize(14);
        doc.text(Math.round(ex.avgFillScore).toString(), valX, labelY + 10, { width: vw });

        doc.fillColor(grey).font('Courier').fontSize(8);
        doc.text('MAKER RATIO', valX, labelY + 32, { width: vw });
        doc.fillColor(white).font('Courier').fontSize(10);
        doc.text(`${Math.round((ex.makerRatio || 0) * 100)}%`, valX, labelY + 42, { width: vw });

        doc.fillColor(grey).font('Courier').fontSize(8);
        doc.text('AVG SLIPPAGE', valX, labelY + 60, { width: vw });
        doc.fillColor(white).font('Courier').fontSize(10);
        doc.text(`${(ex.avgSlippageBps || 0).toFixed(1)} bps`, valX, labelY + 70, { width: vw });

        doc.fillColor(grey).font('Courier').fontSize(8);
        doc.text('TRADES', valX, labelY + 88, { width: vw });
        doc.fillColor(white).font('Courier').fontSize(10);
        doc.text(`${ex.tradeCount}`, valX, labelY + 98, { width: vw });
      });

      // Per-symbol ranking table
      vy += 190;
      doc.fillColor(white).font('Courier-Bold').fontSize(14).text('PER-SYMBOL RANKING', 50, vy);
      vy += 24;

      // Table header
      const symCols = ['SYMBOL', 'BEST VENUE'];
      const symX = [50, 140];
      const exchNames = comparisonData.exchanges.map((e: any) => e.exchange.toUpperCase());
      const exchColX: number[] = [];
      exchNames.forEach((_: string, i: number) => {
        exchColX.push(250 + i * 100);
        symCols.push(exchNames[i]);
        symX.push(250 + i * 100);
      });

      doc.fillColor(grey).font('Courier-Bold').fontSize(9);
      symCols.forEach((col, i) => doc.text(col, symX[i], vy));
      vy += 18;

      // Rows
      if (comparisonData.perSymbolRanking) {
        comparisonData.perSymbolRanking.forEach((sym: any, i: number) => {
          doc.rect(50, vy - 3, pageW - 100, 18).fill(i % 2 === 0 ? '#1a1917' : dark);

          doc.fillColor(white).font('Courier').fontSize(9).text(sym.symbol, 50, vy);
          doc.fillColor(getExchangeColor(sym.bestExchange)).font('Courier-Bold').fontSize(9)
            .text(sym.bestExchange.toUpperCase(), 140, vy);

          exchNames.forEach((exName: string, j: number) => {
            const exLower = exName.toLowerCase();
            const exScore = sym.scoresByExchange[exLower];
            const isHighest = exLower === sym.bestExchange;
            doc.fillColor(isHighest ? '#4ade80' : white).font(isHighest ? 'Courier-Bold' : 'Courier')
              .fontSize(9).text(exScore != null ? exScore.toString() : '—', exchColX[j], vy);
          });

          vy += 18;
        });
      }
    }

    // ─────────────────────────────────────────────────────────
    // LAST PAGE — RECOMMENDATIONS & ACTION PLAN
    // ─────────────────────────────────────────────────────────
    doc.addPage({ size: 'A4', margin: 50 });
    drawBackground();

    doc.fillColor(white).font('Courier-Bold').fontSize(18).text('RECOMMENDATIONS & ACTION PLAN', 50, 50);

    let ry = 90;

    const recs: string[] = auditData.recommendations || [];
    recs.forEach((rec: string, idx: number) => {
      doc.fillColor(gold).font('Courier-Bold').fontSize(36).text((idx + 1).toString().padStart(2, '0'), 50, ry);
      ry += 44;

      const firstDot = rec.indexOf('. ');
      const title = firstDot > 0 ? rec.substring(0, firstDot + 1) : rec;
      const subtitle = firstDot > 0 ? rec.substring(firstDot + 2) : '';

      doc.fillColor(white).font('Courier-Bold').fontSize(14).text(title, 50, ry, { width: pageW - 100 });
      ry = doc.y + 8;

      if (subtitle) {
        doc.fillColor(grey).font('Courier').fontSize(11).text(subtitle, 50, ry, { width: pageW - 100 });
        ry = doc.y + 8;
      }
      ry += 30;
    });

    // Final footer — positioned absolutely at bottom of the last page
    doc.fillColor(grey).font('Courier').fontSize(8).text(
      'FillScore v0.9 beta · fillscore.io · Data encrypted at rest · Not financial advice',
      50, pageH - 60, { align: 'center', width: pageW - 100 }
    );

    doc.end();
    return doc;
  }
}
