import { Router, Request, Response } from 'express';
import rateLimit from 'express-rate-limit';
import { User } from '../models/User';
import { encryptApiKey, hashUserId } from '../utils/encryption';

export const connectRouter = Router();

// Rate limiting: maximum 5 requests per IP every 15 minutes
const connectLimiter = rateLimit({
    windowMs: 15 * 60 * 1000,
    max: 5,
    message: { error: 'Too many connection attempts from this IP, please try again after 15 minutes.' },
});

connectRouter.post('/', connectLimiter, async (req: Request, res: Response) => {
    try {
        const { apiKey, apiSecret, exchange } = req.body;

        // Validate inputs
        if (
            !apiKey || typeof apiKey !== 'string' || apiKey.trim() === '' ||
            !apiSecret || typeof apiSecret !== 'string' || apiSecret.trim() === '' ||
            !['binance', 'bybit'].includes(exchange)
        ) {
            return res.status(400).json({ error: 'Missing required fields' });
        }

        // Encrypt the plain text API key and secret
        const encryptedKeyData = encryptApiKey(apiKey);
        const encryptedSecretData = encryptApiKey(apiSecret);

        // Hash the first 8 characters of the API key to generate a pseudo-random identifier for the user.
        // NOTE (Limitation): This is a simplified demo approach. In a production system with real users,
        // the userId should be firmly tied to a robust authentication session or JWT payload 
        // strictly generated by the backend instead of being seeded from a key fragment.
        const userIdSeed = apiKey.substring(0, 8);
        const finalUserId = hashUserId(userIdSeed);

        // Upsert the user document into MongoDB
        // Using `new: true` to get the created/updated document.
        const userDoc = await User.findOneAndUpdate(
            { userId: finalUserId },
            {
                userId: finalUserId,
                exchange: exchange,
                encryptedApiKey: encryptedKeyData,
                encryptedApiSecret: encryptedSecretData,
            },
            { upsert: true, new: true, setDefaultsOnInsert: true }
        );

        // Return strictly non-sensitive success data. 
        // NEVER log or return the raw keys.
        return res.status(200).json({
            userId: userDoc.userId,
            exchange: userDoc.exchange,
            connectedAt: userDoc.createdAt,
        });
    } catch (error) {
        console.error('Error connecting API keys:', error);
        return res.status(500).json({ error: 'Internal server error while processing API keys' });
    }
});
